language: go

go:
  - tip

install:
  - go get github.com/miekg/dns

script:
  - go test

notifications:
  email:
    recipients:
      - adm@rafael.net.br
    on_success: change
    on_failure: always